services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      TZ: UTC
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    image: fbansept/demo-devops-cda-26-back:0.0.4
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:

