# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: rename .example.env to .env
      run: mv .example.env .env

    - name: Update DB_HOST in application.properties, to database service name in docker-compose (db)
      run: sed -i 's/${DB_HOST}/postgres/' src/main/resources/application.properties

      #    - name: Idem mais en modifiant le .env
#      run: |
#        sed -i 's/^DB_HOST=.*/DB_HOST=postgres' .env

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Extract project version
      run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Build docker image
      run: docker build -t fbansept/demo-devops-cda-26-back .

    - name: Tag image with version from pom.xml
      run: docker tag fbansept/demo-devops-cda-26-back fbansept/demo-devops-cda-26-back:${{ env.VERSION }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: fbansept
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push docker image
      run: docker push fbansept/demo-devops-cda-26-back

    - name: Push docker image with version
      run: docker push fbansept/demo-devops-cda-26-back:${{ env.VERSION }}


